import type { Metadata } from "next";
import { Suspense } from "react";
import LandingLoading from "./loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function LandingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <Suspense fallback={<LandingLoading />}>{children}</Suspense>
    </main>
  );
}
