import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/styles/globals.css";
import "normalize.css/normalize.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`${inter.className} bg-background`}>{children}</body>
    </html>
  );
}
